button:
  include: true
  theme:
    prototype: true
card:
  include: true
  theme:
    prototype: true
checkbox:
  include: true
  theme:
    prototype: true
divider:
  include: true
  theme:
    prototype: true
icons:
  include: true
  theme:
    prototype: true
image:
  include: true
  theme:
    prototype: true
input:
  include: true
  theme:
    prototype: true
label:
  include: true
  theme:
    prototype: true
segment:
  include: true
  theme:
    prototype: true
dropdown:
  include: true
  theme:
    prototype: true
form:
  include: true
  theme:
    prototype: true
menu:
  include: true
  theme:
    prototype: true
message:
  include: true
  theme:
    prototype: true
popup:
  include: true
  theme:
    prototype: true
sidebar:
  include: true
  theme:
    prototype: true
table:
  include: true
  theme:
    prototype: true
mediaquery:
  palm:
    include: true
    widths: true
    layout: true
  lap:
    include: true
    widths: true
    layout: true
  lap-and-up:
    include: true
    widths: true
    layout: true
  portable:
    include: true
    widths: true
    layout: true
  desk:
    include: true
    widths: true
    layout: true
  desk-wide:
    include: true
    widths: true
    layout: true
  under-desk-wide:
    include: true
    widths: true
    layout: true
